FROM node:22-slim

WORKDIR /app

COPY package.json ./
# Установка зависимостей
RUN npm i --legacy-peer-deps

# Копируем остальные файлы
COPY . .

# Build-time переменные для публичных env
ARG NUXT_databaseURL
ARG NUXT_ASSETS_IMAGE_BUCKET
ARG NUXT_SITE_URL
ARG NUXT_TELEGRAM_BOT_USERNAME

# Runtime переменная для приватного токена
ARG NUXT_TELEGRAM_BOT_TOKEN
ARG NUXT_TELEGRAM_ADMIN_CHAT_ID

ARG NUXT_GAMIFICATION_FREEZE_ENABLED
ARG NUXT_GAMIFICATION_FREEZE_CHANCE
ARG NUXT_GAMIFICATION_FREEZE_DURATION
ARG NUXT_GAMIFICATION_FREEZE_COMMISSION
ARG NUXT_CRYPTO_CURRENCY_TOKEN

# Устанавливаем переменные для билда
ENV NUXT_databaseURL=$NUXT_databaseURL
ENV NUXT_ASSETS_IMAGE_BUCKET=$NUXT_ASSETS_IMAGE_BUCKET
ENV NUXT_SITE_URL=$NUXT_SITE_URL
ENV NUXT_TELEGRAM_BOT_USERNAME=$NUXT_TELEGRAM_BOT_USERNAME
ENV NUXT_TELEGRAM_BOT_TOKEN=$NUXT_TELEGRAM_BOT_TOKEN
ENV NUXT_TELEGRAM_ADMIN_CHAT_ID=$NUXT_TELEGRAM_ADMIN_CHAT_ID

ENV NUXT_GAMIFICATION_FREEZE_ENABLED=$NUXT_GAMIFICATION_FREEZE_ENABLED
ENV NUXT_GAMIFICATION_FREEZE_CHANCE=$NUXT_GAMIFICATION_FREEZE_CHANCE
ENV NUXT_GAMIFICATION_FREEZE_DURATION=$NUXT_GAMIFICATION_FREEZE_DURATION
ENV NUXT_GAMIFICATION_FREEZE_COMMISSION=$NUXT_GAMIFICATION_FREEZE_COMMISSION
ENV NUXT_CRYPTO_CURRENCY_TOKEN=$NUXT_CRYPTO_CURRENCY_TOKEN


# Сборка приложения
RUN npm run build

# Удаляем dev зависимости после билда для уменьшения размера
RUN npm prune --production

EXPOSE 3000

# Запуск приложения
CMD ["node", ".output/server/index.mjs"]
